version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: agrolocal_db
    restart: always
    environment:
      MYSQL_DATABASE: agrolocal
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend_agro:
    build: ./backend
    container_name: agrolocal_api
    restart: on-failure
    # Usamos el archivo .env para mayor seguridad
    env_file:
      - ./backend/.env
    depends_on:
      db:   
        condition: service_healthy 
    ports:
      - "3000:3000"

  frontend_agro:
    image: nginx:alpine
    container_name: agrolocal_web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

volumes:
  db_data: